eureka:
  instance:
    prefer-ip-address: true  # Use the instance's IP address when registering with Eureka
  client:
    fetch-registry: true  # Fetch the registry to discover other services
    register-with-eureka: true  # Register this service with Eureka
    service-url:
      defaultZone: http://localhost:8761/eureka
